<script setup>
import { computed, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'

const route = useRoute()
const router = useRouter()

const blogs = [
  { id:1, slug:"how-to-learn-tajweed-ul-quran-online", title:"How to Learn Tajweed ul Quran Online — Complete Beginner's Guide", excerpt:"Tajweed is the set of rules governing the correct pronunciation of the Quran. Learn how you can master Tajweed online with certified teachers.", category:"Tajweed", image:"/assets/images/imageye___-_imgi_5_muslims-reading-from-quran_53876-20958.jpg", imageAlt:"Student learning Tajweed ul Quran online with certified teacher", date:"June 1, 2025", readTime:"5 min read", tags:["tajweed ul quran","learn tajweed online","quran recitation rules","online quran classes"], content:[{heading:"What is Tajweed ul Quran?",text:"Tajweed (تجوید) literally means 'to make better'. In the context of the Holy Quran, Tajweed refers to the set of rules governing the correct pronunciation of Arabic letters during Quranic recitation. Allah SWT revealed the Quran with Tajweed, and it is obligatory (Farz) upon every Muslim to recite the Quran with proper Tajweed."},{heading:"Why is Tajweed Important?",text:"Reciting the Quran without Tajweed can change the meaning of words entirely. The Prophet Muhammad ﷺ said: 'Recite the Quran slowly and distinctly' (Hadith). This shows how important correct recitation is in Islam. A single mispronunciation can completely change the meaning of a Quranic word."},{heading:"Basic Rules of Tajweed You Must Know",text:"The main rules of Tajweed include: Makharij ul Huroof (points of articulation), Sifaat ul Huroof (characteristics of letters), Noon Sakin and Tanween rules, Meem Sakin rules, Madd rules (elongation), Qalqalah (echoing sound), Waqf rules (pausing). Learning these with a qualified teacher is the best approach."},{heading:"How to Learn Tajweed Online at Al Saeed Quran Institute",text:"Our certified Tajweed teachers teach all rules through live one-on-one classes on Zoom or WhatsApp. We start from basic Arabic letter pronunciation and move to advanced recitation rules. Our teachers listen to your recitation, correct mistakes in real-time, and guide you at your own pace. Morning, evening, and weekend classes available."},{heading:"How Long Does it Take to Learn Tajweed?",text:"Basic Tajweed rules can be learned in 3–6 months for a complete beginner with regular classes. Perfecting Tajweed for complete Quran recitation may take 1–2 years. With daily practice of 15–20 minutes, students see significant improvement very quickly."},{heading:"Start Your Free Tajweed Trial Class Today",text:"Al Saeed Quran Institute offers a completely free first trial class with no registration fee. Contact us on WhatsApp at +92 319 8839708. Our experienced teachers are ready to guide you on your Quranic journey. JazakAllah Khair!"}]},
  { id:2, slug:"importance-of-tajweed-in-quran-recitation", title:"The Importance of Tajweed in Quran Recitation — Why Every Muslim Must Learn", excerpt:"Understanding the importance of Tajweed is the first step towards beautiful Quranic recitation.", category:"Tajweed", image:"/assets/images/imageye___-_imgi_9_vector-young-muslim-man-reading-quran_844724-24573.jpg", imageAlt:"Young Muslim man reciting Quran with proper Tajweed rules", date:"May 28, 2025", readTime:"4 min read", tags:["importance of tajweed","quran recitation","tajweed rules"], content:[{heading:"The Quranic Command for Tajweed",text:"Allah SWT says: 'And recite the Quran with measured recitation' (Surah Muzzammil 73:4). Islamic scholars unanimously agree that applying Tajweed rules is an individual obligation (Fard Ayn) on every Muslim."},{heading:"How Tajweed Protects the Meaning",text:"The Arabic language is extremely precise. Tajweed rules were established under the direct guidance of Prophet Muhammad ﷺ to preserve the exact pronunciation of the Quran as it was revealed. This is why Tajweed is considered a protection of the Quran's meaning."},{heading:"Spiritual Benefits of Tajweed",text:"The Prophet ﷺ said: 'The one proficient in Quran recitation will be with the honorable angels, and the one who recites with difficulty will have two rewards' (Bukhari & Muslim). Reciting with Tajweed increases focus, understanding, and spiritual connection with Allah's words."},{heading:"Learn Tajweed with Al Saeed Quran Institute",text:"Our expert Tajweed teachers have helped hundreds of students from Pakistan, UAE, UK, USA and worldwide. Whether you are a beginner or want to refine your recitation, our personalized online classes will take you to the next level. Book your FREE trial class on WhatsApp today!"}]},
  { id:3, slug:"how-to-memorize-quran-online-complete-guide", title:"How to Memorize Quran Online — Complete Guide to Hifz ul Quran", excerpt:"Hifz ul Quran is one of the most noble acts in Islam. Discover proven techniques for online Quran memorization.", category:"Hifz", image:"/assets/images/imageye___-_imgi_8_boy-is-reading-quran-with-headphones_921485-506.jpg", imageAlt:"Child memorizing Quran online — Hifz ul Quran program", date:"May 25, 2025", readTime:"6 min read", tags:["hifz ul quran","memorize quran online","quran memorization"], content:[{heading:"What is Hifz ul Quran?",text:"Hifz ul Quran means complete memorization of the Holy Quran. A person who memorizes the entire Quran is called a Hafiz. The Quran has 30 Paras, 114 Surahs, and 6,236 verses. Becoming a Hafiz is one of the greatest honors in Islam."},{heading:"The Virtues of Becoming a Hafiz",text:"The Prophet ﷺ said: 'The best of you is the one who learns the Quran and teaches it' (Bukhari). On the Day of Judgment, the Hafiz will ascend in ranks for every verse recited. Parents of a Hafiz will be given crowns of light in Jannah."},{heading:"Best Techniques for Online Quran Memorization",text:"Effective Hifz techniques: Sabaq (3–5 new lines daily), Sabaq Para (recent revision), Manzil (old lesson revision). Listening repeatedly before memorizing helps significantly. Recite new lessons in Salah for stronger retention. Consistency of even 30 minutes daily leads to great progress."},{heading:"Our Online Hifz Program",text:"Our program includes daily one-on-one sessions with a certified Hafiz teacher, personalized memorization plan, regular revision sessions, progress tracking, and motivational support. Students from Pakistan, UAE, UK, USA and worldwide are enrolled. Book your free trial Hifz class today!"}]},
  { id:4, slug:"tips-to-complete-hifz-quran-faster", title:"10 Proven Tips to Complete Hifz Quran Faster", excerpt:"These 10 expert-proven tips will help you memorize the Quran more effectively and maintain long-term retention.", category:"Hifz", image:"/assets/images/imageye___-_imgi_13_muslim-family-cartoon-characters_1308-135730.jpg", imageAlt:"Muslim family supporting child in Hifz ul Quran memorization", date:"May 20, 2025", readTime:"5 min read", tags:["hifz tips","quran memorization tips","how to become hafiz"], content:[{heading:"1. Set a Daily Goal",text:"The most important tip is consistency. Set a realistic daily goal and stick to it every day. Even on busy days, memorize at least a few lines. Consistency beats intensity in Hifz."},{heading:"2. Memorize After Fajr",text:"The time after Fajr prayer is the most blessed for memorization. The mind is fresh, the house is quiet, and there are fewer distractions. Scholars always recommend memorizing after Fajr."},{heading:"3. Listen Before Memorizing",text:"Before memorizing a new portion, listen to it multiple times. This helps your brain register the sound pattern, making memorization significantly easier and faster."},{heading:"4–10. Additional Power Tips",text:"4. Repeat each line 20–30 times before moving on. 5. Never skip revision — 70% revision, 30% new. 6. Recite in every Salah. 7. Find a Hifz partner. 8. Understand the meaning through Tafseer. 9. Make sincere dua to Allah. 10. Work with a qualified Hafiz teacher for accountability and guidance."}]},
  { id:5, slug:"what-is-tafseer-ul-quran-importance-benefits", title:"What is Tafseer ul Quran? — Importance, Benefits and How to Learn Online", excerpt:"Tafseer ul Quran is the explanation and commentary of the Holy Quran. Learn what Tafseer is and why it is important.", category:"Tafseer", image:"/assets/images/imageye___-_imgi_5_muslims-reading-from-quran_53876-20958.jpg", imageAlt:"Muslims studying Tafseer ul Quran", date:"May 15, 2025", readTime:"5 min read", tags:["tafseer ul quran","what is tafseer","quran commentary"], content:[{heading:"What is Tafseer ul Quran?",text:"Tafseer (تفسیر) literally means 'explanation'. It is the academic discipline of explaining and interpreting the verses of the Holy Quran — including historical context, connection to other verses and Ahadith, and practical guidance for Muslims."},{heading:"Why is Tafseer Important?",text:"Allah SWT says: 'This is a Book We have sent down, full of blessings, so people may ponder over its verses' (Surah Saad 38:29). Understanding Tafseer transforms your relationship with the Quran and helps you apply its guidance in daily life."},{heading:"Learn Tafseer Online",text:"Our Tafseer program starts from Surah Al-Fatiha and progresses systematically. We teach meaning of each verse, context of revelation, connection with Hadith, and practical lessons. Classes in Urdu and English. Book your free trial class today!"}]},
  { id:6, slug:"top-surahs-tafseer-every-muslim-should-know", title:"Top 10 Surahs Every Muslim Should Learn Tafseer Of", excerpt:"These 10 Surahs contain powerful messages. Learning their Tafseer will transform your understanding of Islam.", category:"Tafseer", image:"/assets/images/imageye___-_imgi_9_vector-young-muslim-man-reading-quran_844724-24573.jpg", imageAlt:"Muslim studying Tafseer of important Surahs", date:"May 10, 2025", readTime:"6 min read", tags:["tafseer important surahs","surah tafseer","quran meaning"], content:[{heading:"1. Surah Al-Fatiha",text:"Surah Al-Fatiha is recited 17 times daily in Salah. Its Tafseer reveals it is a complete dua asking Allah for guidance to the straight path. The Prophet ﷺ called it 'Umm ul Quran'. Understanding its meaning transforms every prayer."},{heading:"2. Surah Al-Baqarah",text:"The longest Surah contains Ayat ul Kursi, the last two verses (Amana Rasool), Islamic laws, and the story of Bani Israel. Its Tafseer provides comprehensive guidance for Muslim life. The Prophet ﷺ said Shaytan does not enter a house where it is recited."},{heading:"3–10. Other Essential Surahs",text:"Surah Al-Kahf (protection from Dajjal), Surah Yaseen (heart of the Quran), Surah Al-Mulk (protection from grave punishment), Surah Al-Rahman (Allah's blessings), Surah Al-Ikhlas (equal to one-third of Quran), Surah Al-Waqiah, Al-Falaq, and Al-Nas. Our Tafseer teachers cover all these with deep explanation."}]},
  { id:7, slug:"what-is-norani-qaida-how-to-learn-for-kids", title:"What is Norani Qaida? — How to Teach Kids Quran Reading from Scratch", excerpt:"Norani Qaida is the foundation of Quranic education. Learn what it is and how to begin online classes.", category:"Norani Qaida", image:"/assets/images/imageye___-_imgi_8_boy-is-reading-quran-with-headphones_921485-506.jpg", imageAlt:"Young child learning Norani Qaida Arabic alphabet online", date:"May 5, 2025", readTime:"4 min read", tags:["norani qaida","norani qaida for kids","learn arabic alphabet"], content:[{heading:"What is Norani Qaida?",text:"Norani Qaida (نورانی قاعدہ) is an educational booklet designed to teach beginners — especially children — the Arabic alphabet and basics of Quranic reading. Compiled by Maulana Noor Muhammad Ludhianvi, it has been used for over a century worldwide."},{heading:"What Does It Teach?",text:"Norani Qaida teaches: all 29 Arabic letters in different forms, short vowels (Zabar, Zer, Pesh), Tanween, Sukoon, Shaddah, Madd letters, joining letters to form words, and basic Tajweed rules. Completing it fully prepares students to read the Holy Quran."},{heading:"Enroll in Online Norani Qaida",text:"Our qualified teachers specialize in teaching young children through fun, engaging online sessions. Classes are 30 minutes, 5 days a week via Zoom or WhatsApp. Students from Pakistan, UAE, UK, USA and worldwide welcome. Book a free trial class today!"}]},
  { id:8, slug:"norani-qaida-lessons-arabic-letters-guide", title:"Norani Qaida Lessons — Complete Guide to Arabic Letters and Quran Reading", excerpt:"Step-by-step guide through all Norani Qaida lessons — Arabic letters, vowels, and progression to Quran reading.", category:"Norani Qaida", image:"/assets/images/imageye___-_imgi_13_muslim-family-cartoon-characters_1308-135730.jpg", imageAlt:"Muslim family teaching Norani Qaida and Arabic letters to children", date:"April 30, 2025", readTime:"5 min read", tags:["norani qaida lessons","arabic letters guide","arabic alphabet beginners"], content:[{heading:"Lesson 1 — Arabic Alphabet",text:"The Arabic alphabet has 29 letters, written and read right to left. Each letter has up to four forms. Norani Qaida begins by teaching students to recognize and pronounce each letter with correct Makhraj (point of articulation)."},{heading:"Lesson 2 — Short Vowels",text:"Three short vowels: Zabar (Fathah) = 'a', Zer (Kasrah) = 'i', Pesh (Dammah) = 'u'. These are written above or below letters and tell you how to pronounce them. Essential for reading the Quran."},{heading:"Lesson 3 — Tanween, Sukoon, Shaddah",text:"Tanween adds 'n' sound to word endings. Sukoon means no vowel — hold briefly. Shaddah means letter is doubled. These three symbols appear constantly throughout the Quran and are essential to master."},{heading:"From Qaida to Quran",text:"After completing all Norani Qaida lessons, students practice joining letters and reading short Quranic phrases. Our teachers ensure strong foundations before students begin the actual Quran. Progress tracked lesson by lesson."}]},
  { id:9, slug:"why-learn-arabic-grammar-to-understand-quran", title:"Why Learning Arabic Grammar is Essential to Understand the Quran", excerpt:"Arabic Grammar is the key to unlocking the true meaning of the Holy Quran. Discover why it is essential.", category:"Arabic Grammar", image:"/assets/images/imageye___-_imgi_9_vector-young-muslim-man-reading-quran_844724-24573.jpg", imageAlt:"Muslim student learning Arabic grammar to understand Holy Quran", date:"April 25, 2025", readTime:"5 min read", tags:["arabic grammar","learn arabic online","nahu sarf","arabic for quran"], content:[{heading:"What is Arabic Grammar?",text:"Arabic grammar is divided into Nahu (Syntax — how words connect in sentences) and Sarf (Morphology — how words change form). Together they give you tools to analyze and understand any Arabic sentence, including Quranic verses."},{heading:"How Grammar Helps Understand the Quran",text:"The Quran was revealed in the most eloquent classical Arabic. Every word is chosen with extreme precision, and its grammatical structure carries deep meaning. Knowing whether a word is subject or object of a sentence changes the entire meaning. Grammar unlocks layers of meaning invisible in translations."},{heading:"Arabic Grammar at Al Saeed Quran Institute",text:"Our program has three levels: Beginner (basic sentence structure), Intermediate (Nahu and Sarf with Quranic application), Advanced (Quranic verse analysis). Classes for students 12+ and adults. Book your free trial via WhatsApp!"}]},
  { id:10, slug:"basic-arabic-grammar-rules-every-quran-student-must-know", title:"10 Basic Arabic Grammar Rules Every Quran Student Must Know", excerpt:"Master these 10 essential Arabic grammar rules and start understanding more of the Holy Quran immediately.", category:"Arabic Grammar", image:"/assets/images/imageye___-_imgi_5_muslims-reading-from-quran_53876-20958.jpg", imageAlt:"Students learning basic Arabic grammar rules for Quran understanding", date:"April 20, 2025", readTime:"6 min read", tags:["arabic grammar rules","basic arabic grammar","arabic for beginners"], content:[{heading:"Rule 1 — Ism, Fiil, Harf",text:"Every Arabic word belongs to: Ism (noun), Fiil (verb), or Harf (particle). Knowing the category is the first step in Arabic grammar analysis."},{heading:"Rule 2 — Mubtada and Khabar",text:"A nominal sentence consists of Mubtada (subject) and Khabar (predicate). 'Allahu Akbar' — Allah (subject) is Greatest (predicate). Both must be in nominative case and match in gender and number."},{heading:"Rules 3–10",text:"3. Muzakkar/Muannath (masculine/feminine). 4. Mufrad/Muthanna/Jama (singular/dual/plural). 5. Faa'il and Maf'ool Bihi (subject and object). 6. Three cases: Raf, Nasb, Jarr. 7. Idhafah (possession). 8. Sifah/Mawsoof (adjective agreement). 9. Verb tenses. 10. Pronoun types. Learn all with Quranic examples at Al Saeed Quran Institute!"}]},
  { id:11, slug:"importance-of-hadith-in-islam-for-beginners", title:"The Importance of Hadith in Islam — A Beginner's Complete Guide", excerpt:"Hadith is the second most important source of Islamic knowledge after the Holy Quran. Learn what Hadith is and why to study it.", category:"Hadis", image:"/assets/images/imageye___-_imgi_5_muslims-reading-from-quran_53876-20958.jpg", imageAlt:"Muslim scholar studying Hadith books", date:"April 15, 2025", readTime:"5 min read", tags:["importance of hadith","what is hadith","learn hadith online"], content:[{heading:"What is Hadith?",text:"Hadith (حدیث) refers to recorded sayings, actions, and approvals of the Prophet Muhammad ﷺ. It is the second primary source of Islamic law and guidance after the Holy Quran. Allah says: 'Whatever the Messenger gives you, take it; whatever he forbids, abstain' (Surah Hashr 59:7)."},{heading:"Why Learn Hadith?",text:"The Quran gives general commands; Hadith provides detailed implementation. The Quran commands Salah, but Hadith tells us exactly how to pray. Without Hadith, we cannot fully practice Islam. Our Mukhtasir Hadis course covers the most important and practical Ahadith for everyday Muslim life."},{heading:"Learn Mukhtasir Hadis Online",text:"Our course covers important Ahadith from authentic collections with Urdu explanation and practical daily life lessons. No prior Arabic knowledge required. Suitable for all ages. Book your free trial class today!"}]},
  { id:12, slug:"40-hadith-nawawi-every-muslim-must-memorize", title:"40 Hadith of Imam Nawawi — Essential Ahadith Every Muslim Must Know", excerpt:"The 40 Hadith of Imam Nawawi are considered the foundation of Islamic knowledge.", category:"Hadis", image:"/assets/images/imageye___-_imgi_9_vector-young-muslim-man-reading-quran_844724-24573.jpg", imageAlt:"Muslim learning the 40 Hadith of Imam Nawawi", date:"April 10, 2025", readTime:"5 min read", tags:["40 hadith nawawi","important hadith","sunnah prophet muhammad"], content:[{heading:"Who was Imam Nawawi?",text:"Imam Yahya ibn Sharaf al-Nawawi (1233–1277 CE) was one of the greatest Islamic scholars. His 40 Hadith collection was compiled to teach the most fundamental principles of Islam through the words of the Prophet ﷺ."},{heading:"Hadith 1 — Actions by Intentions",text:"'Actions are judged by intentions, and each person will get what they intended.' (Bukhari & Muslim). This Hadith teaches that sincerity of intention is the foundation of all Islamic worship."},{heading:"Hadith 2 — Five Pillars",text:"'Islam is built upon five pillars: Testimony, Salah, Zakah, Hajj, and Ramadan fasting.' (Bukhari & Muslim). This Hadith summarizes the entire practical structure of Islam."},{heading:"Study at Al Saeed Quran Institute",text:"Our Mukhtasir Hadis course covers the 40 Nawawi Hadith with detailed Urdu explanation, practical lessons, and memorization assistance. Start with a free trial class today via WhatsApp!"}]},
  { id:13, slug:"essential-daily-duas-every-muslim-should-know", title:"20 Essential Daily Duas Every Muslim Should Know — Mukhtasir Duaen Guide", excerpt:"These 20 daily duas from the Quran and Sunnah will protect and guide you throughout your day.", category:"Duaen", image:"/assets/images/imageye___-_imgi_13_muslim-family-cartoon-characters_1308-135730.jpg", imageAlt:"Muslim family making dua together", date:"April 5, 2025", readTime:"5 min read", tags:["daily duas","duas from quran","mukhtasir duaen"], content:[{heading:"Why Learn Daily Duas?",text:"Dua is the weapon of the believer. Allah says: 'Call upon Me, I will respond to you' (Surah Ghafir 40:60). The Prophet ﷺ taught specific duas for every occasion — waking up, eating, entering home, sleeping, and more."},{heading:"Morning Duas",text:"After Fajr: Ayat ul Kursi (protection all day), Surah Al-Ikhlas, Al-Falaq, Al-Nas (3 times each), 'Asbahna wa asbahal mulku lillah', and morning dua of the Prophet ﷺ. These create a spiritual shield for the entire day."},{heading:"Learn All Essential Duas",text:"Our Mukhtasir Duaen course covers 50+ duas from Quran and Sunnah with Arabic text, transliteration, Urdu translation, and audio pronunciation. Perfect for all ages including children. Book your free trial via WhatsApp!"}]},
  { id:14, slug:"powerful-duas-from-quran-for-daily-life", title:"10 Most Powerful Duas from the Holy Quran for Daily Life", excerpt:"The Quran contains the most powerful duas. These 10 Quranic duas will transform your daily worship.", category:"Duaen", image:"/assets/images/imageye___-_imgi_5_muslims-reading-from-quran_53876-20958.jpg", imageAlt:"Muslim making dua with Quran", date:"March 30, 2025", readTime:"5 min read", tags:["duas from quran","powerful quranic duas","dua for protection"], content:[{heading:"1. Dua for Guidance — Surah Al-Fatiha",text:"'Ihdinas-siraatal mustaqeem' — Guide us to the straight path (1:6). Greatest dua in the Quran, recited 17 times daily in Salah. Asks Allah for guidance in every matter of life."},{heading:"2. Dua of Prophet Ibrahim",text:"'Rabbana-ghfir li wa li-waalidayya...' — Our Lord, forgive me and my parents (Ibrahim 14:41). Teach your children to recite this dua for you daily."},{heading:"3. Dua for Anxiety",text:"'Hasbiyallahu la ilaha illa huwa...' — Allah is sufficient for me (Tawbah 9:129). Recite 7 times morning and evening for relief from all worries."},{heading:"More Quranic Duas",text:"Dua of Prophet Yunus in the whale, Dua for righteous spouse and children (Furqan 25:74), Dua of Prophet Musa, 'Rabbi zidni ilma' for knowledge, Ayat ul Kursi before sleeping, and 'Rabbana atina fid-dunya hasanatan'. All covered in our Mukhtasir Duaen course."}]},
  { id:15, slug:"why-learn-tarjama-tul-quran-benefits", title:"Why Every Muslim Should Learn Tarjama tul Quran — Benefits and How to Start", excerpt:"Understanding the Quran's translation is a life-changing experience. Discover the immense benefits of Tarjama.", category:"Tarjama", image:"/assets/images/imageye___-_imgi_5_muslims-reading-from-quran_53876-20958.jpg", imageAlt:"Muslim reading Tarjama ul Quran to understand the meaning", date:"March 25, 2025", readTime:"5 min read", tags:["tarjama tul quran","quran translation urdu","understand quran meaning"], content:[{heading:"What is Tarjama tul Quran?",text:"Tarjama (ترجمہ) means translation. Tarjama tul Quran is learning the word-by-word or verse-by-verse translation of the Holy Quran in your native language — Urdu or English. It allows millions of non-Arabic speaking Muslims to access its guidance."},{heading:"Why is Tarjama Important?",text:"Allah says: 'This is a Book full of blessings, so they may reflect on its verses' (Surah Saad 38:29). Simply reciting without understanding is beneficial, but Tarjama transforms your relationship with the Quran. It changes your Salah, strengthens Iman, and helps you apply Quranic guidance daily."},{heading:"Start Tarjama Classes",text:"Our Tarjama course begins from Surah Al-Fatiha and progresses systematically. Every verse explained in simple Urdu or English. Available for ages 12 and above. No prior Islamic knowledge required. Book your free trial class via WhatsApp today!"}]},
  { id:16, slug:"understand-quran-without-knowing-arabic", title:"Can You Understand the Quran Without Knowing Arabic? — Tarjama Guide", excerpt:"Many Muslims wonder if they can understand the Quran without Arabic. The answer is yes — through Tarjama.", category:"Tarjama", image:"/assets/images/imageye___-_imgi_13_muslim-family-cartoon-characters_1308-135730.jpg", imageAlt:"Muslim family reading Quran translation together", date:"March 20, 2025", readTime:"4 min read", tags:["understand quran without arabic","quran translation","quran meaning urdu"], content:[{heading:"Can Non-Arabic Muslims Understand the Quran?",text:"Absolutely! Over 80% of the world's 1.8 billion Muslims do not speak Arabic natively. Learning Tarjama in Urdu, English, or your native language is completely valid and highly recommended. The Companions memorized small Quranic portions and deeply understood them before moving forward."},{heading:"How Tarjama Changes Your Salah",text:"Imagine reciting 'Al-hamdu lillahi Rabbil alameen' without knowing it means 'All praise is for Allah, Lord of all worlds'. Knowing the Tarjama completely transforms the spiritual experience of Salah. Your prayers become meaningful conversations with Allah."},{heading:"Begin Your Tarjama Journey",text:"Our Tarjama course makes the meaning of every Quranic verse accessible in simple Urdu or English. Classes for teenagers to elderly. Students from Pakistan, UAE, UK, USA worldwide enrolled. Book your FREE first class on WhatsApp!"}]}
]

const blog = computed(() => blogs.find(b => b.slug === route.params.slug))

const relatedBlogs = computed(() => {
  if (!blog.value) return []
  return blogs.filter(b => b.category === blog.value.category && b.slug !== blog.value.slug).slice(0, 3)
})

onMounted(() => {
  if (!blog.value) {
    router.push('/blog')
    return
  }
  document.title = `${blog.value.title} | Al Saeed Quran Institute`
  const desc = document.querySelector('meta[name="description"]')
  if (desc) desc.setAttribute('content', blog.value.excerpt)
})
</script>

<template>
  <div v-if="blog" style="min-height: 100vh; background: #f9fafb;">

    <!-- Hero Image -->
    <div style="position: relative; height: 400px; overflow: hidden;">
      <img
        :src="blog.image"
        :alt="blog.imageAlt"
        :title="blog.title"
        style="width: 100%; height: 100%; object-fit: cover;"
      />
      <div style="position: absolute; inset: 0; background: linear-gradient(to bottom, rgba(124,58,237,0.4), rgba(109,40,217,0.85));"></div>
      <div style="position: absolute; inset: 0; display: flex; flex-direction: column; justify-content: flex-end; padding: 40px 20px;">
        <div style="max-width: 800px; margin: 0 auto; width: 100%;">
          <span style="background: rgba(255,255,255,0.2); color: white; font-size: 12px; font-weight: 700; padding: 5px 14px; border-radius: 50px; display: inline-block; margin-bottom: 14px;">
            {{ blog.category }}
          </span>
          <h1 style="color: white; font-size: clamp(1.4rem, 3vw, 2.2rem); font-weight: 900; margin: 0 0 16px; line-height: 1.3;">{{ blog.title }}</h1>
          <div style="display: flex; align-items: center; gap: 20px; flex-wrap: wrap;">
            <span style="color: rgba(255,255,255,0.8); font-size: 13px;">📅 {{ blog.date }}</span>
            <span style="color: rgba(255,255,255,0.8); font-size: 13px;">⏱ {{ blog.readTime }}</span>
            <span style="color: rgba(255,255,255,0.8); font-size: 13px;">✍️ Al Saeed Quran Institute</span>
          </div>
        </div>
      </div>
    </div>

    <!-- Content -->
    <div style="max-width: 800px; margin: 0 auto; padding: 48px 20px;">

      <!-- Breadcrumb -->
      <nav style="margin-bottom: 32px; font-size: 13px; color: #9ca3af; display: flex; align-items: center; gap: 8px; flex-wrap: wrap;">
        <router-link to="/" style="color: #7c3aed; text-decoration: none;">Home</router-link>
        <span>›</span>
        <router-link to="/blog" style="color: #7c3aed; text-decoration: none;">Blog</router-link>
        <span>›</span>
        <span style="color: #6b7280;">{{ blog.category }}</span>
        <span>›</span>
        <span style="color: #374151; font-weight: 600;">{{ blog.title.substring(0, 40) }}...</span>
      </nav>

      <!-- Excerpt -->
      <div style="background: #f5f3ff; border-left: 4px solid #7c3aed; border-radius: 0 14px 14px 0; padding: 20px 24px; margin-bottom: 40px;">
        <p style="color: #4c1d95; font-size: 15px; font-style: italic; margin: 0; line-height: 1.7;">{{ blog.excerpt }}</p>
      </div>

      <!-- Blog Body -->
      <article>
        <div v-for="(section, i) in blog.content" :key="i" style="margin-bottom: 36px;">
          <h2 style="font-size: 20px; font-weight: 800; color: #111827; margin: 0 0 14px; padding-bottom: 10px; border-bottom: 2px solid #f5f3ff;">
            {{ section.heading }}
          </h2>
          <p style="color: #4b5563; font-size: 15px; line-height: 1.9; margin: 0;">{{ section.text }}</p>
        </div>
      </article>

      <!-- Tags -->
      <div style="margin: 40px 0; padding: 24px; background: white; border-radius: 16px; box-shadow: 0 2px 12px rgba(0,0,0,0.05);">
        <p style="font-weight: 700; color: #374151; font-size: 13px; margin: 0 0 12px;">🏷️ Tags:</p>
        <div style="display: flex; flex-wrap: wrap; gap: 8px;">
          <span v-for="tag in blog.tags" :key="tag"
            style="background: #f5f3ff; color: #7c3aed; font-size: 12px; font-weight: 600; padding: 5px 14px; border-radius: 50px; border: 1px solid #ede9fe;">
            #{{ tag }}
          </span>
        </div>
      </div>

      <!-- CTA Box -->
      <div style="background: linear-gradient(135deg,#7c3aed,#6d28d9); border-radius: 24px; padding: 36px; text-align: center; margin: 40px 0;">
        <h3 style="color: white; font-size: 22px; font-weight: 900; margin: 0 0 10px;">
          Want to Learn {{ blog.category }}?
        </h3>
        <p style="color: #ddd6fe; font-size: 14px; margin: 0 0 24px;">
          Book a FREE trial class at Al Saeed Quran Institute. No registration fee. Certified teachers. Zoom & WhatsApp classes.
        </p>
        <a href="https://wa.me/923198839708?text=Assalamualaikum%20I%20read%20your%20blog%20and%20want%20to%20book%20a%20free%20trial%20class"
          target="_blank"
          style="display: inline-flex; align-items: center; gap: 10px; background: white; color: #7c3aed; font-weight: 800; padding: 14px 32px; border-radius: 50px; text-decoration: none; font-size: 14px; box-shadow: 0 6px 20px rgba(0,0,0,0.15);">
          <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="#7c3aed">
            <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z"/>
          </svg>
          Book FREE Trial Class Now
        </a>
      </div>

      <!-- Related Posts -->
      <div v-if="relatedBlogs.length" style="margin-top: 48px;">
        <h3 style="font-size: 20px; font-weight: 900; color: #111827; margin: 0 0 24px;">Related Articles</h3>
        <div style="display: grid; grid-template-columns: repeat(auto-fill, minmax(220px, 1fr)); gap: 20px;">
          <router-link v-for="related in relatedBlogs" :key="related.slug"
            :to="`/blog/${related.slug}`"
            style="background: white; border-radius: 16px; overflow: hidden; box-shadow: 0 4px 14px rgba(0,0,0,0.06); text-decoration: none; transition: all 0.3s; display: block;"
            onmouseover="this.style.transform='translateY(-4px)'; this.style.boxShadow='0 12px 28px rgba(124,58,237,0.12)'"
            onmouseout="this.style.transform='translateY(0)'; this.style.boxShadow='0 4px 14px rgba(0,0,0,0.06)'">
            <img :src="related.image" :alt="related.imageAlt" loading="lazy"
              style="width: 100%; height: 130px; object-fit: cover;" />
            <div style="padding: 16px;">
              <span style="color: #7c3aed; font-size: 11px; font-weight: 700;">{{ related.category }}</span>
              <p style="color: #111827; font-size: 13px; font-weight: 700; margin: 6px 0 0; line-height: 1.4;">{{ related.title.substring(0, 60) }}...</p>
            </div>
          </router-link>
        </div>
      </div>
    </div>
  </div>

  <div v-else style="min-height: 100vh; display: flex; align-items: center; justify-content: center;">
    <div style="text-align: center;">
      <p style="font-size: 48px; margin-bottom: 16px;">📖</p>
      <h2 style="color: #111827; font-weight: 900; margin: 0 0 8px;">Article not found</h2>
      <router-link to="/blog" style="color: #7c3aed; font-weight: 700; text-decoration: none;">← Back to Blog</router-link>
    </div>
  </div>
</template>
